using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NWN.Native.Generators.Diagnostics;
using NWN.Native.Generators.Extensions;
using NWN.Native.Generators.Symbols;

namespace NWN.Native.Generators.Generators;

[Generator]
internal class CStructGenerator : IIncrementalGenerator
{
  private const string PInvokeLibraryName = "NWNX_DotNET";
  private const string LibraryImportClassName = "PInvoke";

  private const string StructAttributeTypeName = "NWN.Native.Attributes.CStructAttribute";
  private const string StructAttributeClassName = "CStructAttribute";

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    IncrementalValuesProvider<CStructContextInfo?> structDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName<CStructContextInfo?>(
        StructAttributeTypeName,
        (node, _) => node is StructDeclarationSyntax,
        (generatorContext, _) => GetSemanticTargetForGeneration(generatorContext))
      .Where(info => info is not null);

    IncrementalValueProvider<(Compilation, ImmutableArray<CStructContextInfo?>)> compilation = context.CompilationProvider.Combine(structDeclarations.Collect());
    context.RegisterSourceOutput(compilation, (sourceProductionContext, source) => Execute(source!, sourceProductionContext));
  }

  private static CStructContextInfo? GetSemanticTargetForGeneration(GeneratorAttributeSyntaxContext context)
  {
    if (context.TargetNode is not StructDeclarationSyntax structDeclaration)
    {
      return null;
    }

    AttributeData? attribute = context.Attributes.FirstOrDefault(a => a.AttributeClass?.Name == StructAttributeClassName);
    return attribute != null ? new CStructContextInfo(structDeclaration) : null;
  }

  private void Execute((Compilation compilation, ImmutableArray<CStructContextInfo> contextClasses) output, SourceProductionContext productionContext)
  {
    foreach (CStructContextInfo contextStruct in output.contextClasses)
    {
      SemanticModel semanticModel = output.compilation.GetSemanticModel(contextStruct.Context.SyntaxTree, true);
      if (semanticModel.GetDeclaredSymbol(contextStruct.Context) is INamedTypeSymbol typeSymbol)
      {
        CStructTypeInfo typeInfo = new(typeSymbol);
        productionContext.AddSource(contextStruct.GeneratedFileName, GenerateStruct(contextStruct, typeInfo, productionContext));
      }
    }
  }

  private static string GenerateStruct(CStructContextInfo contextInfo, CStructTypeInfo typeInfo, SourceProductionContext productionContext)
  {
    List<CMethodInfo> targetMethods = GetTargetMethods(typeInfo);
    if (targetMethods.Count == 0)
    {
      return string.Empty;
    }

    using StringWriter stringWriter = new();
    using IndentedTextWriter textWriter = new(stringWriter, "  ");

    textWriter.WriteLine("// <auto-generated/>");
    textWriter.WriteLine("using System;");
    textWriter.WriteLine();

    foreach (SyntaxNode syntaxNode in contextInfo.Parents)
    {
      switch (syntaxNode)
      {
        case BaseNamespaceDeclarationSyntax namespaceDecl:
          textWriter.BeginScope(namespaceDecl.GetDeclarationString());
          break;
        case TypeDeclarationSyntax typeDecl:
          textWriter.BeginScope(typeDecl.GetDeclarationString());
          break;
        default:
          productionContext.ReportDiagnostic(Diagnostic.Create(DiagnosticConstants.UnknownSyntaxNode, syntaxNode.GetLocation(), syntaxNode.GetType().ToString()));
          throw new Exception($"Unexpected SyntaxNode {contextInfo.GetType().Name}");
      }
    }

    textWriter.BeginScope(contextInfo.Context.GetDeclarationString());
    {
      GenerateStructMethods(textWriter, typeInfo, targetMethods);
      textWriter.WriteLine();
      GenerateLibraryImportInstanceMethods(textWriter, typeInfo, targetMethods);
    }
    textWriter.EndScope();

    for (int i = contextInfo.Parents.Count - 1; i >= 0; i--)
    {
      SyntaxNode syntaxNode = contextInfo.Parents[i];
      switch (syntaxNode)
      {
        case TypeDeclarationSyntax:
        case BaseNamespaceDeclarationSyntax:
          textWriter.EndScope();
          break;
        default:
          throw new Exception($"Unexpected SyntaxNode {contextInfo.GetType().Name}");
      }
    }

    return stringWriter.ToString();
  }

  private static List<CMethodInfo> GetTargetMethods(CStructTypeInfo typeInfo)
  {
    List<CMethodInfo> methods = [];
    foreach (CMethodInfo methodInfo in typeInfo.Methods)
    {
      if (!string.IsNullOrEmpty(methodInfo.EntryPoint))
      {
        methods.Add(methodInfo);
      }
    }

    return methods;
  }

  private static void GenerateStructMethods(IndentedTextWriter textWriter, CStructTypeInfo type, List<CMethodInfo> targetMethods)
  {
    foreach (CMethodInfo method in targetMethods)
    {
      if (method.IsStatic)
      {
        GenerateLibraryImportMethod(textWriter, type, method, method.Accessibility);
      }
      else
      {
        GenerateShimMethod(textWriter, type, method);
      }

      textWriter.WriteLine();
    }
  }

  private static void GenerateShimMethod(IndentedTextWriter textWriter, CStructTypeInfo type, CMethodInfo method)
  {
    List<string> parameters = method.Parameters;
    List<string> arguments = ["pThis", ..method.ParameterNames];

    textWriter.BeginScope($"{method.Accessibility} partial {method.ReturnType} {method.Name}({string.Join(", ", parameters)})");
    {
      textWriter.BeginScope($"fixed ({type.Name}* pThis = &this)");
      {
        if (method.ReturnType is not ("void" or "Void"))
        {
          textWriter.WriteLine($"return {LibraryImportClassName}.{method.Name}({string.Join(", ", arguments)});");
        }
        else
        {
          textWriter.WriteLine($"{LibraryImportClassName}.{method.Name}({string.Join(", ", arguments)});");
        }
      }
      textWriter.EndScope();
    }
    textWriter.EndScope();
  }

  private static void GenerateLibraryImportInstanceMethods(IndentedTextWriter textWriter, CStructTypeInfo type, List<CMethodInfo> targetMethods)
  {
    textWriter.BeginScope($"private static partial class {LibraryImportClassName}");
    {
      foreach (CMethodInfo method in targetMethods)
      {
        if (!method.IsStatic)
        {
          GenerateLibraryImportMethod(textWriter, type, method, "public");
          textWriter.WriteLine();
        }
      }
    }
    textWriter.EndScope();
  }

  private static void GenerateLibraryImportMethod(IndentedTextWriter textWriter, CStructTypeInfo type, CMethodInfo method, string accessibility)
  {
    textWriter.WriteLine($"""[System.Runtime.InteropServices.DllImport("{PInvokeLibraryName}", EntryPoint = "{method.EntryPoint}", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]""");

    if (method.IsStatic)
    {
      List<string> parameters = [..method.Parameters];
      textWriter.WriteLine($"{accessibility} static extern partial {method.ReturnType} {method.Name}({string.Join(", ", parameters)});");
    }
    else
    {
      List<string> parameters = [$"{type.Name}* pThis", ..method.Parameters];
      textWriter.WriteLine($"{accessibility} static extern {method.ReturnType} {method.Name}({string.Join(", ", parameters)});");
    }
  }
}
