using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NWN.Native.Generators.Diagnostics;
using NWN.Native.Generators.Extensions;

namespace NWN.Native.Generators.Generators;

[Generator]
public class FixedArrayGenerator : ISourceGenerator
{
  private const string ArrayNamespace = "NWN.Native.API";
  private const string StructAttributeTypeName = "NWN.Native.Attributes.FixedArrayAttribute";

  public void Initialize(GeneratorInitializationContext context) { }

  public void Execute(GeneratorExecutionContext context)
  {
    INamedTypeSymbol? fixedArrayAttribute = context.Compilation.GetTypeByMetadataName(StructAttributeTypeName);
    if (fixedArrayAttribute == null)
    {
      return;
    }

    HashSet<int> arraySizes = CollectDistinctArraySizes(context, fixedArrayAttribute);
    if (arraySizes.Count == 0)
    {
      return;
    }

    context.AddSource("FixedArrays.g.cs", GenerateArrayStructs(arraySizes.OrderBy(size => size).ToList()));
  }

  private HashSet<int> CollectDistinctArraySizes(GeneratorExecutionContext context, INamedTypeSymbol fixedArrayAttribute)
  {
    HashSet<int> arraySizes = [];
    foreach (SyntaxTree syntaxTree in context.Compilation.SyntaxTrees)
    {
      SemanticModel semanticModel = context.Compilation.GetSemanticModel(syntaxTree);
      IEnumerable<StructDeclarationSyntax> structDeclarations = syntaxTree.GetRoot().DescendantNodes()
        .OfType<StructDeclarationSyntax>();

      IEnumerable<IFieldSymbol> fields = CollectFields(semanticModel, structDeclarations);
      foreach (IFieldSymbol field in fields)
      {
        ImmutableArray<AttributeData> attributes = field.GetAttributes();
        foreach (AttributeData attribute in attributes)
        {
          if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, fixedArrayAttribute))
          {
            continue;
          }

          int size = (int)(attribute.ConstructorArguments.First().Value ?? 0);
          if (size <= 0)
          {
            context.ReportDiagnostic(Diagnostic.Create(DiagnosticConstants.FixedArraySizeTooSmall, field.Locations.FirstOrDefault()));
            continue;
          }

          arraySizes.Add(size);
        }
      }
    }

    return arraySizes;
  }

  private List<IFieldSymbol> CollectFields(SemanticModel semanticModel, IEnumerable<StructDeclarationSyntax> structDeclarations)
  {
    List<IFieldSymbol> fields = [];
    foreach (StructDeclarationSyntax structDeclaration in structDeclarations)
    {
      if (semanticModel.GetDeclaredSymbol(structDeclaration) is INamedTypeSymbol structSymbol)
      {
        fields.AddRange(structSymbol.GetMembers().OfType<IFieldSymbol>());
      }
    }

    return fields;
  }

  private string GenerateArrayStructs(List<int> arraySizes)
  {
    using StringWriter stringWriter = new();
    using IndentedTextWriter textWriter = new(stringWriter, "  ");

    textWriter.WriteLine("// <auto-generated/>");
    textWriter.WriteLine("using System.Runtime.CompilerServices;");
    textWriter.WriteLine();
    textWriter.WriteLine($"namespace {ArrayNamespace};");
    textWriter.WriteLine();

    foreach (int arraySize in arraySizes)
    {
      textWriter.WriteLine($"[InlineArray({arraySize})]");
      textWriter.BeginScope($"public struct FixedArray{arraySize}<T> where T : unmanaged");
      {
        textWriter.WriteLine("public T Element0;");
      }
      textWriter.EndScope();
      textWriter.WriteLine();
    }

    return stringWriter.ToString();
  }
}
